// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreApplication.Models;

namespace StoreApplication.Migrations.StoreDB
{
    [DbContext(typeof(StoreDBContext))]
    partial class StoreDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StoreApplication.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("productId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Price")
                        .HasColumnName("price")
                        .HasColumnType("money");

                    b.Property<byte[]>("ProductImage")
                        .HasColumnName("productImage");

                    b.Property<string>("ProductName")
                        .HasColumnName("productName")
                        .HasMaxLength(50);

                    b.HasKey("ProductId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("StoreApplication.Models.UserCart", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnName("productId");

                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("cartId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasMaxLength(450);

                    b.Property<int>("Quantity")
                        .HasColumnName("quantity");

                    b.HasKey("ProductId", "CartId");

                    b.ToTable("UserCart");
                });

            modelBuilder.Entity("StoreApplication.Models.UserCart", b =>
                {
                    b.HasOne("StoreApplication.Models.Product", "Product")
                        .WithMany("UserCart")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__UserCart__produc__7C4F7684");
                });
#pragma warning restore 612, 618
        }
    }
}
